version: '3.7'
services:
  mariaDB:
    container_name: MariaDB
    image: mariadb:10.3
    volumes:
      - type: volume
        source: mariaDB-storage
        target: /var/lib/mysql
    #      - type: bind
    #        source: ../volumes/MariaDB
    #        target: /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Bangkok
      MYSQL_DATABASE: azbilDB
      MYSQL_ROOT_PASSWORD: Azbil@system123!
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/usr/bin/mysql --user=root --password=Azbil@system123!",
          "--execute",
          'SHOW DATABASES'
        ]
      interval: 3s
      timeout: 1s
      retries: 5

  influxDB:
    container_name: InfluxDB
    image: influxdb:1.8.9
    #    image: tutum/influxdb
    expose:
      - 8086
    volumes:
      - type: volume
        source: influxDB-storage
        target: /var/lib/influxdb
    environment:
      VIRTUAL_HOST: influx.azbil-dev.online
      # LETSENCRYPT_HOST: influx.azbil-dev.online
      # LETSENCRYPT_EMAIL: info@innotechdev.co.th
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: Azbil@system123!
      INFLUXDB_DB: azbilDB
    restart: always

  mongoDB:
    container_name: MongoDB
    image: mongo:4.2
    volumes:
      - type: volume
        source: mongoDB-storage
        target: /var/lib/mysql
    #      - type: bind
    #        source: ../volumes/MongoDB
    #        target: /data/db
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Bangkok
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Azbil@system123!
      MONGO_INITDB_DATABASE: azbilDB
    restart: always
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 3s
      timeout: 1s
      retries: 5
  mongo-express:
    container_name: Mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDB
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: azbil@123!
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: azbil@123!
    restart: always

volumes:
  mariaDB-storage:
  influxDB-storage:
  mongoDB-storage:


# networks:
#   default:
#     external:
#       name: auto-lets-encrypt
