version: '3.7'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana_network
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:


networks:
  grafana_network:
    external:
      name: db_network
