version: '3.7'
services:
  mongoDB:
    container_name: MongoDB
    image: mongo:latest
    volumes:
      - type: volume
        source: /mongoDB-storage
        target: /var/lib/mysql
    #      - type: bind
    #        source: ../volumes/MongoDB
    #        target: /data/db
    ports:
      - 27017:27017
    networks:
      - db
    environment:
      TZ: Asia/Bangkok
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: asset123
      MONGO_INITDB_DATABASE: asset_management
    restart: always
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 3s
      timeout: 1s
      retries: 5


volumes:
  mongoDB-storage:

networks:
  db:
    driver: bridge
    name: db_network
